// <copyright file="SuffixNamingStrategy.cs" company="DisposableDatabases">
//     Copyright (c) 2022 Joshua B Raymond. All rights reserved.
// </copyright>

using CommunityToolkit.Diagnostics;
using DisposableDatabases.Interfaces.Strategies;

namespace DisposableDatabases.Strategies.Naming.Decorators;

/// <summary>
/// A decorator for the <see cref="INamingStrategy" /> interface that adds a suffix to the generated database name.
/// </summary>
public class SuffixNamingStrategy : INamingStrategy
{
	/// <summary>
	/// The underlying database naming strategy that is being decorated to allow for additional functionality,
	/// such as suffixing generated database names.
	/// </summary>
	private readonly INamingStrategy _namingStrategy;

	/// <summary>
	/// The suffix value to be appended to the database name generated by the underlying database naming strategy.
	/// </summary>
	private readonly string _suffix;

	/// <summary>
	/// Initializes a new instance of the <see cref="SuffixNamingStrategy" /> class.
	/// </summary>
	/// <param name="namingStrategy">The underlying database naming strategy to be decorated.</param>
	/// <param name="suffix">The suffix to append to the database name generated by the underlying strategy.</param>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="namingStrategy" /> is null.</exception>
	/// <exception cref="ArgumentException">Thrown when <paramref name="suffix" /> is null or consists solely of white space.</exception>
	public SuffixNamingStrategy(INamingStrategy namingStrategy, string suffix)
	{
		Guard.IsNotNull(namingStrategy);
		Guard.IsNotNullOrWhiteSpace(suffix);

		_namingStrategy = namingStrategy;
		_suffix = suffix;
	}

	/// <summary>
	/// Generates a database name by appending a specified suffix to the name provided by the underlying naming strategy.
	/// </summary>
	/// <returns>A database name with the specified suffix.</returns>
	public string GenerateName()
	{
		return $"{_namingStrategy.GenerateName()}{_suffix}";
	}
}
