// <copyright file="DatabaseNamingStrategyPrefixDecorator.cs" company="DisposableDatabases">
//     Copyright (c) 2022 Joshua B Raymond. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;
using CommunityToolkit.Diagnostics;
using DisposableDatabases.Interfaces.Strategies;

namespace DisposableDatabases.Strategies.DatabaseNaming.Decorators;

/// <summary>
/// A decorator for the <see cref="IDatabaseNamingStrategy" /> interface that adds a prefix to the generated database name.
/// </summary>
public class DatabaseNamingStrategyPrefixDecorator : IDatabaseNamingStrategy
{
	/// <summary>
	/// The underlying database naming strategy that is being decorated to allow for additional functionality,
	/// such as prefixing generated database names.
	/// </summary>
	private readonly IDatabaseNamingStrategy _databaseNamingStrategy;

	/// <summary>
	/// The prefix value to be prepended to the database name generated by the underlying database naming strategy.
	/// </summary>
	private readonly string _prefix;

	/// <summary>
	/// Initializes a new instance of the <see cref="DatabaseNamingStrategyPrefixDecorator" /> class.
	/// </summary>
	/// <param name="databaseNamingStrategy">The underlying database naming strategy to be decorated.</param>
	/// <param name="prefix">The prefix to prepend to the database name generated by the underlying strategy.</param>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="databaseNamingStrategy" /> is null.</exception>
	/// <exception cref="ArgumentException">Thrown when <paramref name="prefix" /> is null or consists solely of white space.</exception>
	public DatabaseNamingStrategyPrefixDecorator([NotNull] IDatabaseNamingStrategy? databaseNamingStrategy, [NotNull] string? prefix)
	{
		Guard.IsNotNull(databaseNamingStrategy);
		Guard.IsNotNullOrWhiteSpace(prefix);

		_databaseNamingStrategy = databaseNamingStrategy;
		_prefix = prefix;
	}

	/// <summary>
	/// Generates a database name by prepending a specified prefix to the name provided by the underlying naming strategy.
	/// </summary>
	/// <returns>A database name with the specified prefix.</returns>
	public string GenerateDatabaseName()
	{
		return $"{_prefix}{_databaseNamingStrategy.GenerateDatabaseName()}";
	}
}
