// <copyright file="DatabaseNamingStrategySuffixDecorator.cs" company="DisposableDatabases">
//     Copyright (c) 2022 Joshua B Raymond. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;
using CommunityToolkit.Diagnostics;
using DisposableDatabases.Interfaces.Strategies;

namespace DisposableDatabases.Strategies.DatabaseNaming.Decorators;

/// <summary>
/// A decorator for the <see cref="IDatabaseNamingStrategy" /> interface that adds a suffix to the generated database name.
/// </summary>
public class DatabaseNamingStrategySuffixDecorator : IDatabaseNamingStrategy
{
	/// <summary>
	/// The underlying database naming strategy that is being decorated to allow for additional functionality,
	/// such as suffixing generated database names.
	/// </summary>
	private readonly IDatabaseNamingStrategy _databaseNamingStrategy;

	/// <summary>
	/// The suffix value to be appended to the database name generated by the underlying database naming strategy.
	/// </summary>
	private readonly string _suffix;

	/// <summary>
	/// Initializes a new instance of the <see cref="DatabaseNamingStrategySuffixDecorator" /> class.
	/// </summary>
	/// <param name="databaseNamingStrategy">The underlying database naming strategy to be decorated.</param>
	/// <param name="suffix">The suffix to append to the database name generated by the underlying strategy.</param>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="databaseNamingStrategy" /> is null.</exception>
	/// <exception cref="ArgumentException">Thrown when <paramref name="suffix" /> is null or consists solely of white space.</exception>
	public DatabaseNamingStrategySuffixDecorator([NotNull] IDatabaseNamingStrategy? databaseNamingStrategy, [NotNull] string? suffix)
	{
		Guard.IsNotNull(databaseNamingStrategy);
		Guard.IsNotNullOrWhiteSpace(suffix);

		_databaseNamingStrategy = databaseNamingStrategy;
		_suffix = suffix;
	}

	/// <summary>
	/// Generates a database name by appending a specified suffix to the name provided by the underlying naming strategy.
	/// </summary>
	/// <returns>A database name with the specified suffix.</returns>
	public string GenerateDatabaseName()
	{
		return $"{_databaseNamingStrategy.GenerateDatabaseName()}{_suffix}";
	}
}
